WITH RECURSIVE TREE_CTE AS (
    SELECT ID, PARENT_ID, 1 AS LEVEL
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, C.LEVEL + 1
    FROM ECOLI_DATA AS E
    JOIN TREE_CTE C ON E.PARENT_ID = C.ID
)

SELECT ID
FROM TREE_CTE
WHERE LEVEL = 3
ORDER BY ID