SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER,
COUNT(DISTINCT(O.USER_ID)) AS USERS
FROM USER_INFO U JOIN ONLINE_SALE O ON U.USER_ID = O.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC, GENDER ASC

# select year(sales_date) YEAR ,month(sales_date) MONTH, GENDER, count(distinct(o.USER_ID)) USERS
# from ONLINE_SALE o join USER_INFO u
# on o.USER_ID = u.USER_ID
# WHERE gender is not null
# group by year(sales_date), month(sales_date), gender
# ORDER BY YEAR, MONTH, GENDER