SELECT OUTS.ANIMAL_ID, OUTS.NAME
FROM ANIMAL_INS INS # 동물 보호소에 들어온 동물 정보
RIGHT OUTER JOIN ANIMAL_OUTS OUTS # 입양 보낸 정보
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE INS.ANIMAL_ID IS NULL
ORDER BY OUTS.ANIMAL_ID, OUTS.NAME