WITH CTE_FOOD AS (
    SELECT PRODUCT_ID, AMOUNT, DATE_FORMAT(PRODUCE_DATE, '%Y-%m-%d') AS PRODUCE_DATE
    FROM FOOD_ORDER
    WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
)

SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(F.AMOUNT * P.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT P
JOIN CTE_FOOD F ON P.PRODUCT_ID = F.PRODUCT_ID
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC