WITH ICE_CTE AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
)

SELECT F.FLAVOR
FROM FIRST_HALF F
JOIN ICE_CTE I ON F.FLAVOR = I.FLAVOR
GROUP BY F.FLAVOR
ORDER BY SUM(F.TOTAL_ORDER + I.TOTAL_ORDER) DESC
            
LIMIT 3