WITH TABLE_GRADE AS (SELECT 
  EMP_NO,
  CASE 
    WHEN AVG(SCORE) >= 96 THEN 'S'
    WHEN AVG(SCORE) >= 90 THEN 'A'
    WHEN AVG(SCORE) >= 80 THEN 'B'
    ELSE 'C'
  END AS GRADE
FROM HR_GRADE
GROUP BY YEAR, EMP_NO
)

SELECT DISTINCT(HE.EMP_NO), HE.EMP_NAME, TG.GRADE, CASE
    WHEN TG.GRADE = 'S' THEN HE.SAL * 0.2
    WHEN TG.GRADE = 'A' THEN HE.SAL * 0.15
    WHEN TG.GRADE = 'B' THEN HE.SAL * 0.1
    ELSE HE.SAL * 0
END AS BONUS
FROM HR_EMPLOYEES HE
JOIN HR_GRADE HG ON HE.EMP_NO = HG.EMP_NO
JOIN TABLE_GRADE TG ON TG.EMP_NO = HE.EMP_NO