WITH REVIEW_COUNT AS (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
)

SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE P
JOIN REVIEW_COUNT C ON P.MEMBER_ID = C.MEMBER_ID
JOIN REST_REVIEW R ON R.MEMBER_ID = C.MEMBER_ID
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT